"""add database module tables

Revision ID: 7948a72d8bbd
Revises: 10caabfa1946
Create Date: 2026-05-04 14:12:38.811068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7948a72d8bbd'
down_revision: Union[str, None] = '10caabfa1946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibodies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('clone', sa.String(length=64), nullable=True),
    sa.Column('clonality', sa.String(length=16), nullable=True),
    sa.Column('applications', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('catalog_number', sa.String(length=64), nullable=True),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('dilution', sa.String(length=64), nullable=True),
    sa.Column('box_location', sa.String(length=64), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cell_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.Column('tissue', sa.String(length=128), nullable=True),
    sa.Column('passage_number', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=128), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plasmids',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('backbone', sa.String(length=128), nullable=True),
    sa.Column('insert_name', sa.String(length=255), nullable=True),
    sa.Column('length_bp', sa.Integer(), nullable=True),
    sa.Column('resistance', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('host_strain', sa.String(length=64), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('box_location', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('primers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('length_nt', sa.Integer(), nullable=True),
    sa.Column('tm_celsius', sa.Float(), nullable=True),
    sa.Column('gc_percent', sa.Float(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('box_location', sa.String(length=64), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.Column('genotype', sa.Text(), nullable=True),
    sa.Column('parent_strain_id', sa.UUID(), nullable=True),
    sa.Column('box_location', sa.String(length=64), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_strain_id'], ['strains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('viruses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('serotype', sa.String(length=32), nullable=True),
    sa.Column('transgene', sa.String(length=255), nullable=True),
    sa.Column('titer', sa.Float(), nullable=True),
    sa.Column('volume_uL', sa.Float(), nullable=True),
    sa.Column('bsl_level', sa.Integer(), nullable=True),
    sa.Column('box_location', sa.String(length=64), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='available', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plasmid_features',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plasmid_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('start_bp', sa.Integer(), nullable=False),
    sa.Column('end_bp', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=2), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['plasmid_id'], ['plasmids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plasmid_features')
    op.drop_table('viruses')
    op.drop_table('strains')
    op.drop_table('primers')
    op.drop_table('plasmids')
    op.drop_table('cell_lines')
    op.drop_table('antibodies')
    # ### end Alembic commands ###
